# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI - Build with Maven

on: [ push ]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 14 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: scripts/build.sh
        env:
          IS_COMPILE: true

  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build and test the project
        run: scripts/build.sh
        env:
          CI_SECURE_ENV_VARS: true
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          GITHUB_TOKEN: ${{ github.token }}